### ISSUE TITLE
Question on BlueGraph compared to other Libraries

### ISSUE THREAD

**Issue by BradKML** [BlueBrain/BlueGraph#93]
1. How is BlueGraph different compared to CDLib (with iGraph and NetworkX)?
  - There are not enough variety of centrality measures compared to NetworkX
    - https://github.com/networkx/networkx/issues/4973
    - https://github.com/networkx/networkx/discussions/4808
    - https://github.com/networkx/networkx/discussions/5062
  - There are not enough community detection algorithms compared to CDLib
    - https://github.com/GiulioRossetti/cdlib
    - https://github.com/GiulioRossetti/cdlib/issues/178
2. How is BLueGraph different compared to KarateClub (regarding the number of node embedding algorithms)?
  - https://github.com/benedekrozemberczki/karateclub

**Comment by BrandonKMLee** [comment]
A bit of a dumb question: is there any way of wrapping networkx into being as fast as graph-tool?

**Comment by eugeniashurko** [comment]
I don't think so (though this question should be forwarded rather to `networkx` or `graph-tool` maintainers).
From [graph-tool's main page](https://graph-tool.skewed.de/)

> Graph-tool is an efficient Python module for manipulation and statistical analysis of graphs (a.k.a. networks). Contrary to most other Python modules with similar functionality, the core data structures and algorithms are implemented in C++, making extensive use of template metaprogramming, based heavily on the Boost Graph Library. This confers it a level of performance that is comparable (both in memory usage and computation time) to that of a pure C/C++ library.
